# Generated by Django 5.2.4 on 2025-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_details_alter_student_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='details',
            name='address2',
            field=models.TextField(default='Default Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='pincode',
            field=models.CharField(default=400000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='state',
            field=models.CharField(default='eg. Maharashtra', max_length=100),
            preserve_default=False,
        ),
    ]
