# Generated by Django 5.2.4 on 2025-08-02 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_address_details_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='address2',
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
