# Generated by Django 5.2.4 on 2025-08-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='in_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='out_time',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='weekly_off',
            field=models.CharField(blank=True, default='Saturday,Sunday', max_length=100, null=True),
        ),
    ]
